---

- name: Install/Setup Docker images and containers on Daedalus
  hosts: daedalus
  become: true
  become_user: root
  become_method: sudo
  tags:
    - buildbot
    - buildbot-master
  vars:
    known_hosts: "{{gitlab_keys.stdout}}"
    ntel_release_uri:    "https://{{nexus_hostname}}/repository/ntel-release"
    ntel_beta_uri:       "https://{{nexus_hostname}}/repository/ntel-unofficial"
    ntel_sstate_uri:     "https://{{nexus_hostname}}/repository/ntel-sstate"
    ptxdist_release_uri: "https://{{nexus_hostname}}/repository/ptxdist-release"
    ptxdist_beta_uri:    "https://{{nexus_hostname}}/repository/ptxdist-unofficial"
  tasks:
    - add_host:
        name: nexus
        groups: services
        ip_addr: "{{ nexus_ip_addr }}"
        uri: "repository"
    - name: Scan Gitlab ssh keys
      command: ssh-keyscan {{gitlab_hostname}}
      register: gitlab_keys
      changed_when: false
    - name: Build and start the Buildbot master container
      import_role:
        name: buildbot-master

- name: Setup Buildbot worker system
  hosts: builder
  become: true
  become_user: root
  become_method: sudo
  tags:
    - buildbot
    - buildbot-worker
  vars:
    asset_host: "https://{{nexus_hostname}}/repository"
    asset_user: "buildbot"
    asset_password: "{{nexus_buildbot_password}}"
    asset_downloads:   "{{ asset_host }}/download"
    asset_orphans:     "{{ asset_host }}/orphans"
    asset_debian:      "{{ asset_host }}/debian"
    asset_sourceforge: "{{ asset_host }}/sourceforge"
    asset_gnu:         "{{ asset_host }}/gnu"
    asset_xorg:        "{{ asset_host }}/xorg"
    asset_kernel:      "{{ asset_host }}/kernel/linux"
    asset_pypi:        "{{ asset_host }}/pypi"
    buildbot_master: "{{ buildbot_hostname }}"
    known_hosts: "{{ gitlab_keys.stdout }}"
  tasks:
    - name: Scan Gitlab ssh keys
      command: ssh-keyscan {{gitlab_hostname}}
      register: gitlab_keys
      changed_when: false
      tags:
        - always
    - name: Build and start the Buildbot worker container
      import_role:
        name: buildbot-worker-ntel
      tags:
        - buildbot-worker-ntel
    - name: Build and start the Buildbot worker container
      import_role:
        name: buildbot-worker-ptxdist
      tags:
        - buildbot-worker-ptxdist
