---
#=========================================================
# TFTP Server Container
#---------------------------------------------------------
- name: Build docker image ----- Test Station tftp server
  docker_image:
    build:
      path: "{{ docker_projects_dir }}/{{ build_system_docker_repos.TestStation_tftp_server.dir_name }}"
      pull: yes
    name: "{{ name_prefix }}teststation_tftp_image"
    source: build
    state: "{{ image_build_state_nondata }}"
    force_source: "{{ docker_image_force_build }}"

- name: Start docker container - Test Station tftp server
  docker_container:
    comparisons: {'*': strict}
    command: "/usr/sbin/in.tftpd --foreground --user tftp --address {{ build_ip_addr }}:69 -s /opt/tftp_files"
    detach: True
    image: "{{ name_prefix }}teststation_tftp_image"
    name: "{{ name_prefix }}TestStation_tftp_server"
    network_mode: host
    state: "{{ container_start_state_nondata }}"
    restart_policy: '{{ docker_restart_policy }}'
    volumes_from:
      - "{{ name_prefix }}TestStation_tftp_data"

# Docker doesn't do this automatically when network_mode=host
- name: Open firewall for tftp
  firewalld:
    permanent: yes
    service: tftp
    state: enabled
    zone: public
