---
- name: Check preconditions
  assert:
    that:
    - buildsystem_database_root_password is defined
    - buildsystem_database_build_password is defined
    - svn_username is defined
    - svn_password is defined

- import_tasks: grab_files/ncd.yml
  vars:
    username: "{{ svn_username }}"
    password: "{{ svn_password }}"
    repo: "{{ ncd_repo }}"
    working_directory: "{{ local_working_directory }}"


- import_tasks: grab_files/web.yml
  vars:
    working_directory: "{{ local_working_directory }}"
    web_site_name: BuildSystem
    web_site_repo_url: "{{ buildsystem_repo }}"
    database_name: "{{ buildsystem_database_name }}"
    database_user: "root"
    database_password: "{{ buildsystem_database_root_password }}"
    server_directory: "{{ buildsystem_directory }}"


- import_tasks: create_db_user.yml
  vars:
    db_host:                 "{{ build_ip_addr }}"
    db_admin_user:           "root"
    db_admin_user_password:  "{{ buildsystem_database_root_password }}"
    db_new_user:             "build"
    db_new_user_password:    "{{ buildsystem_database_build_password }}"
    db_new_user_permissions: ["SELECT ON *.*"]
    db_grant_cmd_end:        ";"

- import_tasks: create_db_user.yml
  vars:
    db_host:                 "{{ build_ip_addr }}"
    db_admin_user:           "root"
    db_admin_user_password:  "{{ buildsystem_database_root_password }}"
    db_new_user:             "remote_update"
    db_new_user_password:    "{{ buildsystem_database_remote_update_password }}"
    db_new_user_permissions: ["SELECT ON *.*"]
    db_grant_cmd_end:        ";"

- import_tasks: create_db_user.yml
  vars:
    db_host:                 "{{ build_ip_addr }}"
    db_admin_user:           "root"
    db_admin_user_password:  "{{ buildsystem_database_root_password }}"
    db_new_user:             "replication"
    db_new_user_password:    "{{ buildsystem_database_replication_password }}"
    db_new_user_permissions: ["SELECT ON *.*"]
    db_grant_cmd_end:        ";"
