---
- name: Check for local directory to store the web site code exists
  run_once: true
  sudo: false
  local_action:
    module: file
    mode: 0775
    path: "{{ working_directory }}"
    state: directory

- name: Downloading web site code
  run_once: true
  sudo: false
  local_action:
    module: git
    repo: "{{ web_site_repo_url }}"
    dest: "{{ working_directory }}/{{ web_site_name }}"
    force: yes

- name: Set datebase name in website code
  sudo: false
  local_action: replace
    dest="{{ working_directory }}/{{ web_site_name }}/settings.py"
    regexp="(.*'NAME':\s*').*('.*)"
    replace='\1{{ database_name }}\2'

- name: Set database user in website code
  sudo: false
  local_action: replace
    dest="{{ working_directory }}/{{ web_site_name }}/settings.py"
    regexp="(.*'USER':\s*').*('.*)"
    replace='\1{{ database_user }}\2'

- name: Set database user password in website code
  sudo: false
  local_action: replace
    dest="{{ working_directory }}/{{ web_site_name }}/settings.py"
    regexp="(.*'PASSWORD':\s*).*"
    replace='\1"{{ database_password }}",'


- name: Sychronizing web files to server
  synchronize:
    src: "{{ working_directory }}/{{ web_site_name }}/"
    dest: "{{ server_directory }}"
    owner: no
