---
# file: roles/docker-gitlab/tasks/main.yaml

- name: Check preconditions
  assert:
    that:
    - gitlab_db_password is defined

- name: docker_container.conf dir
  file:
    state: directory
    path: '{{ gitlab_config_dir }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
    recurse: no

# *****************************************************************************
# backup script part

- name: Assemble dir for backup scripts
  file:
    path: /usr/libexec/bacula/backup-scripts
    state: directory

- name: before_backup script part
  template:
    src: before_backup.j2
    dest: /usr/libexec/bacula/backup-scripts/55.before_backup.gitlab

- name: after_backup script part
  template:
    src: after_backup.j2
    dest: /usr/libexec/bacula/backup-scripts/55.after_backup.gitlab

# *****************************************************************************
# update the Docker restore config

# contains the database username and password
- name: make gitlab.rb
  template:
    src: gitlab.rb-{{gitlab_version}}.j2
    dest: '{{ gitlab_config_dir }}/gitlab.rb'
    backup: yes
    owner: root
    group: root
    mode: 'u=rw,g=r,o='
- name: exists - state file
  stat:
    path: '{{ gitlab_config_dir }}/restore.date.txt'
    get_checksum: False
    get_md5: False
  register: st_gitlab_restore

# *****************************************************************************
# Create the data volumes

- name: backup-volume container (gitlab)
  docker_volume:
    name: '{{ gitlab_bv_name }}'

- name: config-volume container (gitlab)
  docker_volume:
    name: '{{ gitlab_cv_name }}'

- name: data-volume container (gitlab)
  docker_volume:
    name: '{{ gitlab_dv_name }}'

# *****************************************************************************
# Create the gitlab container

- name: create container (gitlab)
  docker_container:
    detach: true
    hostname: '{{ gitlab_hostname }}'
    image: '{{ gitlab_image_name }}'
    name: '{{ gitlab_container_name }}'
    networks:
      - name: '{{ docker_network_frontend }}'
        aliases:
          - '{{ gitlab_hostname }}'
    ports: '{{ gitlab_port_args }}'
    purge_networks: true
    restart_policy: '{{ docker_restart_policy }}'
    state: present
    volumes:
      - '{{ openssl_dv_name }}:/etc/ssl/private:z'
      - '{{ gitlab_cv_name }}:/etc/gitlab:z'
      - '{{ gitlab_dv_name }}:/var/opt/gitlab:z'
      - '{{ gitlab_bv_name }}:{{ gitlab_bv_mountpoint }}:z'

- name: Copy config into container
  command: >
    docker cp
    '{{ gitlab_config_dir }}/gitlab.rb'
    '{{ gitlab_container_name }}:/etc/gitlab/gitlab.rb'

- name: start container (gitlab)
  docker_container:
    name: '{{ gitlab_container_name }}'
    state: started

- name: Wait for gitlab to be fully running
  docker_health:
    name: '{{ gitlab_container_name }}'
  register: health
  retries: 60
  delay: 5
  until: health.Health.Status == "healthy"

# *****************************************************************************
# restore?

- include_tasks: restore.yml
  when: st_gitlab_restore.stat.exists == False

# *****************************************************************************
# final maintenance

- name: reconfigure gitlab for updated configuration
  command: >
    docker exec -t {{ gitlab_container_name }} gitlab-ctl reconfigure
  register: reconfigure
  retries: 10
  delay: 30
  until: reconfigure is success

- name: ensure all migrations are complete
  command: >
    docker exec -t {{ gitlab_container_name }} gitlab-rake db:migrate
  register: migrate
  retries: 10
  delay: 30
  until: migrate is success

- name: run a diagnostic check over the application
  command: >
    docker exec -t {{ gitlab_container_name }} gitlab-rake gitlab:check
  register: check
  retries: 10
  delay: 30
  until: check is success

# *****************************************************************************
# post-install configuration

- include_tasks: configuration.yml
  become: false
